### ISSUE TITLE
新規登録

### ISSUE THREAD

**Issue by mayu0130** [mayu0130/Cafe-app#10]
## タスク概要
`gem devise`を用いて新規登録機能を作成する

## TODO
- [x] Gemfileに`gem devise`記述後、インストール
- [x] `rails generate  devise:install`を実行
- [x] `rails g devise:views`を実行
- [x] `rails generate devise User`を実行
- [x] 日本語化
- [x] ビューを調整する
- [x] TailwindCSSの追加
