### ISSUE TITLE
ログアウト

### ISSUE THREAD

**Issue by mayu0130** [mayu0130/Cafe-app#12]
## タスク概要
ログアウト機能を実装する

## TODO
- [x] `app/views/layouts/application.html.erb`ビューの調整

- パスの設定
- { turbo_method: :delete }

- [x] `app/javascript/packs/application.js`の記述確認

- [x] `application_controller.rb`に以下を追加
```
　def after_sign_out_path_for(resource_or_scope)
    new_user_session_path 
  end
```
