### ISSUE TITLE
goggle認証

### ISSUE THREAD

**Issue by mayu0130** [mayu0130/Cafe-app#140]
## タスク概要
`omniauth-google-oauth2`を使ってGoogleログインを実装

## TODO
**Goggle cloud consle**
- [ ] Google Cloud側の設定をする

**認証情報**
- [ ] 以下ををクレデンシャルファイルに保存
```
google:
  google_client_id: ***
  google_client_secret: ***
```
**Gemのインストール**
- [ ] 以下を`Gemfile`に記述しインストール
```
gem "devise", "~> 4.9"
gem 'omniauth'
gem 'omniauth-rails_csrf_protection'
gem 'omniauth-github'
gem 'omniauth-google-oauth2'
```
**クレデンシャルを追加する**
- [ ] `app/config/initializers/devise.rb`に以下を追加
```
Devise.setup.do |config|
...
# config.omniauth :github, 'APP_ID', 'APP_SECRET', scope: 'user,public_repo'
config.omniauth :google_oauth2, 
                 Rails.application.credentials.google[:google_client_id],
                 Rails.application.credentials.google[:google_client_secret]
end
```
**MVC**
- [ ] Userモデルを設定
- [ ] Userモデルにて`self.from_omniauth`アクションを作成する
- [ ] コールバック用ルーティング定義する
- [ ] コールバック用コントローラ定義する
- [ ] コールバックコントローラーにgoogle_oauth2アクションを作成する
- [ ] ユーザーモデルにて`self.from_omniauth`アクションを作成する
- [ ] ビューを作成する

**Oauth用カラムを追加**
- [ ] UserテーブルにOauth用の`uid`と`provider`カラムを追加

## 参考記事
[[Rails]deviseとomniauthによるgoogleログイン](https://zenn.dev/redheadchloe/articles/81dec8a2ba5e4a)
[Rails 7 × Googleログイン – omniauth-google-oauth2で簡単OAuth認証](https://zenn.dev/shunjuio/articles/b9ffb6565b7409)
