### ISSUE TITLE
画像アップロード時のS3との接続設定

### ISSUE THREAD

**Issue by mayu0130** [mayu0130/Cafe-app#141]
## 概要
AWS S3を用いて本番環境で画像が永続的に表示されるようにする

## TODO

- [ ] AWS S3バケット・IAM作成
- [ ] Gemのインストール
```
gem 'aws-sdk-s3', require: false
gem 'dotenv-rails'
```
- [ ] `config/storage.yml`の記述
- [ ] `config/environments/production.rb`の記述
- [ ] `.env`ファイルの作成
***
## 参考記事
[[Rails]Active Storageの画像をAWS S3へ保存する](https://zenn.dev/redheadchloe/articles/e924ab767b40d5)
