### ISSUE TITLE
Rspecの導入

### ISSUE THREAD

**Issue by mayu0130** [mayu0130/Cafe-app#142]
## 概要
Rspecでコントローラのテストを導入する

## TODO
- [ ] `spec/requests`配下に該当のファイルを作成
- [ ] `spec/requests/samples_spec.rb`に`describe`と`it`で検証すべき項目を記述
- [ ] `describe`と`it`で検証すべき項目を記述に沿ってテストを書き込む
- [ ] `bundle exec rspec spec/requests/samples_spec.rb`でテストが通るか確認

## 参考記事
[【Ruby on Rails】コントローラーの単体テストコードについてまとめ(RSpec)](https://qiita.com/mumucochimu/items/0a25aa3189d69bf0d8ad)
