### ISSUE TITLE
フラッシュメッセージの表示

### ISSUE THREAD

**Issue by mayu0130** [mayu0130/Cafe-app#19]
## タスク概要
フラッシュメッセージを表示させる

## TODO

- [x] `application.helper.rb`にフラッシュメッセージの記述
- [x] フラッシュメッセージを表示させたいコントローラを確認する
- [x] `app/views/application.html.erb`でビューを作成
- [x] TailwindCSSの追加

**Comment by mayu0130** [comment]
## タスク概要
フラッシュメッセージを表示させる

## TODO
- [ ] フラッシュメッセージを表示させたいコントローラを確認する
- [ ] ` app/views/application.html.erb`でビューを作成
- [ ] TailwindCSSの追加
