### ISSUE TITLE
プロフィール詳細ページ

### ISSUE THREAD

**Issue by mayu0130** [mayu0130/Cafe-app#27]
## タスク概要
プロフィール詳細ページを作成
- 共通ヘッダーにあるプロフィールリンクからプロフィール詳細ページに飛ぶように遷移

## TODO

- [x] profileテーブルを作成
- [x] userモデルとprofileモデルにリレーションを記述する
- [x] ルーティング・コントローラ・ビューの作成
- [x] 共通ヘッダーのプロフィールリンクのパスを設定
- [x] posts/index.html.erbの記事一覧部分をパーシャル化する
- [x] 自分の投稿した投稿一覧を表示させる（`current_user`）
- [x] TailwindCSSの追加
