### ISSUE TITLE
ニックネームとプロフィール画像を該当ビューに表示

### ISSUE THREAD

**Issue by mayu0130** [mayu0130/Cafe-app#82]
## タスク概要
該当ビューにプロフィール画像とニックネーム（avatar・nickname）を表示させる

## TODO
- [x]  投稿一覧（avatar・nickname）
- [x]  投稿詳細（avatar・nickname）
- [x] 投稿詳細のコメント閲覧部分（nickname）
- [x]  プロフィール詳細の投稿閲覧部分（avatar・nickname）
- [x]  共通ヘッダーのプロフィール（avatar）
- [x] 投稿詳細のプロフィール編集ボタンの出し分け
